### ISSUE TITLE
Is it not possible to print TRLMemo across multiple pages?

### ISSUE THREAD

**Issue by Soner-A** [fortesinformatica/fortesreport-ce#175]
Is it not possible to print TRLMemo across multiple pages?
I have a memo that has to be printed over 2 pages, it does not follow previous items, it makes page break. Look at this picture:
![fortesttest3error](https://user-images.githubusercontent.com/30119932/36550428-308435ea-17ed-11e8-8de5-434497a0450d.png)
I have here simple example for Lazarus:
[https://1drv.ms/u/s!AvJGv-C_3b-WgQ1jFJDzeIT3fc1A](url)

**Comment by Soner-A** [comment]
Forget this, you can close this. It looks like TRLMemo is not made for this kind of text.
I think FortesReport needs Stringlist-Band with stringsproperty and only one TRLabel in inside to print all text line for line.
It is mostly used for text above and under items table in invoide.

I am making designer for fortesreport, it is half done can edit, load and preview.
I need two things this one and a small table inside a band to list tax rates line for line in one band.
When i solve this issues i complete the designer.
Your report is really good, thanks for this.

**Comment by dopidaniel** [comment]
Thanks for improving Fortes Report functionalities...

I´m not the author of it... Fortes Report original author is "Ronaldo Moreira and Márcio Martins"...

We use Fortes Report in our Open Source Project... https://www.projetoacbr.com.br/

I´ve made a lot of changes in sources, in order to make it compatible with Lazarus/FPC... So Marcio give me commit access... ;)
