### ISSUE TITLE
Erro ao instalar Fortes Report em Lazarus Linux

### ISSUE THREAD

**Issue by elidorio** [fortesinformatica/fortesreport-ce#93]
Olá,

Ao tentar instalar o Fortes Report no Lazarus/ Linux esta apresentando o erro abaixo:
RLXLSXFileFormat.pas(497,3) Error: Argument can't be assigned to

![captura de tela de 2016-02-18 19 12 20](https://cloud.githubusercontent.com/assets/2966579/13164041/6b1c8f82-d699-11e5-886b-e00611c00695.png)

**Comment by jone22i** [comment]
Comigo também ocorreu, alguém conseguiu uma solução?

**Comment by zoran-vucenovic** [comment]
Sorry, I do not speek portuguese. This is not Linux problem, but 64-bit problem. You cannot compile Fortes on 64-bit target because you cannot cast pointer type (which is 64 bit) to Integer (which is 32-bit) without loss. And when it is on left side of the assignment this is compile-time error.
This is easily fixable by replacing Integer with PtrInt in both places in this line, that is:
PtrInt(ItemPtr) := PtrInt(FHeapPtr) + FHeapLength;
However, the biggest problem with this is that we can't be sure how many mixing Pointers and Integers are there, when they are not on left-side of the assignment - all these places will be much more difficult to find, because then the code will pass in compile time, but it will make serious issues once in runtime. The program may even work well for many times and once you get errors which are very hard to track.

**Comment by EMBBlaster** [comment]
@zoran-vucenovic 
Why can't we change to code below?
ItemPtr := Pointer(Integer(FHeapPtr) + FHeapLength);

**Comment by zoran-vucenovic** [comment]
@EMBBlaster 
That is even more dangerous, because it will pass compilation, but you might just lose data (this is exactly the situation I explained in lower part of my previous message).
Here, Integer(FHeapPtr) is asking for trouble! It passes compilation, so this bug is very hard to find.

On 64-bit system pointer size is 64-bit, and Integer type is still 32-bit. So, casting variable FHeapPtr, which is of type Pointer to Integer is casting 64-bit type to 32-bit type. For example if FHeapPtr is 100C34601 (hex), then when you cast it to Integer, you will get C34601 (hex). The big number just cannot fit in 32-bit, so after executing this line ItemPtr will point to quite wrong place in memory, and you will get corrupted memory.

**Comment by EMBBlaster** [comment]
@zoran-vucenovic Oh... That's makes sense. Thanks for your time explaining. I think that we could change that code using "IFDEF" and selecting the correct Integer type to pointer. Anyway, if I understood right, we would need to search trough all the code to find all the pointers operations and correct them.

**Comment by eduardomrj** [comment]
Alguma atualização disponível para resolver o problema?

**Comment by EMBBlaster** [comment]
Basicamente a solução é: Instale o Lazarus 32 bits.

**Comment by dopidaniel** [comment]
Uso o Fortes Report em Linux 64 bits... utilizamos ele na compilação do ACBrMonitorPLUS
Já tentou instalá-lo em um Lazarus mais recente que o 1.4.4 ?

**Comment by juliomar** [comment]
Favor testar a situação acima
caso tenha novos problemas favor abrir novo issue com maiores detalhes.
